#端口号
server:
  port: 8081
#数据源
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_traffic?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456

  mvc:
      view:
           prefix: "/WEB-INF/pages/"


  servlet:
       multipart:
         max-file-size: 100MB
         max-request-size: 100MB
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

  resources:
    static-locations: classpath:/static/

mybatis:
  type-aliases-package: com.reverie.domain


#obs:
#    endPoint: obs.cn-north-4.myhuaweicloud.com
#    ak: E9MOTADUKWHLBSPKRBO1
#    sk: 1cz6rCBX3djJKc9yuTHFaHrBNFuL5nLqgtUtF966
#    bucketLocation: cn-north-4
#    bucketName: obs-ogs-test
